# ── Goal Definition ──
# timeout: Indicates the number of seconds after which the operation is considered timed out if it has not been completed since digging began.
float32 timeout

---
# ── Result Definition ──
# result_code:
# 0 = Normal termination (block dug)
# 1 = No block in line of sight (could not start and terminated immediately)
# 2 = Interrupted due to timeout
# 3 = Received a cancellation request (optional)
# and other statuses are returned as int32
int32 result_code

